### PR TITLE
fix: provider initialization

### LINKED ISSUE #168: Flags status is incorrect when an already started unleash client is passed to flag provider
### Describe the bug

I have a case that I want to pass an already started unleash client to the unleash flag provider. When I do that, `flagsReady` (returned from `useFlagsStatus` hook) returns `false` even though the client is started and ready.

Here is a reproducible example: https://stackblitz.com/edit/vitejs-vite-elpthg?file=src%2FApp.tsx.

As far as I see, this behaviour is this way due to calling the `readyCallback` only when we get the `ready` event from the client. In my case, this event is never sent since the client is already ready before the flag provider component is initialized:
https://github.com/Unleash/proxy-client-react/blob/4656873b1ddb699f6268fb0b13c719e451d3a84b/src/FlagProvider.tsx#L77

I wonder if this is intentional and whether the case I mentioned is an intended way of using unleash client or not. Happy to contribute if it is decided to be an actual bug - but I might still need some pointers.

### SDK information (language and version)

`unleash-proxy-client@3.4.0` and `@unleash/proxy-client-react@4.2.3`

### PR DESCRIPTION
**Pull request by Tymek**
There was a bug where the flagsReady status, returned from the useFlagsStatus hook, remains false even when an already started Unleash client is passed to the Unleash flag provider. This occurred despite the client being initialized and ready.

Closes #168 

## About the changes
- [x] test showing the issue
- [x] externalizing SDK state
  - [x] Upgrade unleash-proxy-client dependency to version 3.5.1.
- [x] check state in Provider
  - [x] Updated the initialization logic to check if the client is already ready and set flagsReady appropriately.

### CODE REVIEW

File: src/FlagProvider.tsx [hunk 1]
```diff
@@ -37,13 +39,13 @@ const FlagProvider: React.FC<React.PropsWithChildren<IFlagProvider>> = ({
   const [flagsReady, setFlagsReady] = React.useState(
     Boolean(
       unleashClient
-        ? customConfig?.bootstrap && customConfig?.bootstrapOverride !== false
+        ? (customConfig?.bootstrap && customConfig?.bootstrapOverride !== false) || unleashClient.isReady?.()
```
Comment (FredrikOseberg) [inline src/FlagProvider.tsx:42]: Isn't this the only significant line here? Why do we need these other changes?

File: src/FlagProvider.tsx [hunk 2]
```diff
@@ -90,37 +92,24 @@ const FlagProvider: React.FC<React.PropsWithChildren<IFlagProvider>> = ({
       if (client.current) {
         client.current.off('error', errorCallback);
         client.current.off('ready', readyCallback);
-        client.current.off('recovered', clearErrorCallback)
-        client.current.stop();
+        client.current.off('recovered', clearErrorCallback);
+        if (stopClient) {
```
Comment (FredrikOseberg) [inline src/FlagProvider.tsx:96]: Why do we need a stopClient property?

File: src/FlagProvider.tsx (hunk 1 above)
Comment (Tymek) [reply src/FlagProvider.tsx:42]: It's about adding the ability to pass initialized client. Error state is also needed to make sure state kept in React SDK is matching the one from initialized client

File: .github/workflows/build.yml [hunk 3]
```diff
@@ -12,7 +12,7 @@ jobs:
     runs-on: ubuntu-latest
     strategy:
       matrix:
-        node-version: [18.x, 20.x, 21.x]
+        node-version: [18.x, 20.x, 21.x, 22.x]
```
Comment (Tymek) [inline .github/workflows/build.yml:15]:
```suggestion
        node-version: [18.x, 20.x, 21.x]
```

File: .github/workflows/build.yml [hunk 4]
```diff
@@ -22,7 +22,7 @@ jobs:
           node-version: ${{ matrix.node-version }}
 
       - name: 📌 Install
-        run: yarn
+        run: yarn install --frozen-lockfile
```
Comment (Tymek) [inline .github/workflows/build.yml:25]:
```suggestion
        run: yarn
```

File: src/FlagProvider.tsx (hunk 2 above)
Comment (FredrikOseberg) [reply src/FlagProvider.tsx:96]: Makes sense. Thank you for clarifying.

**Review by FredrikOseberg — APPROVED** [review]
LGTM
